### ISSUE TITLE
Trying to use 2 different instances of the input

### ISSUE THREAD

**Issue by gabriel-george** [livelybone/vue-datepicker#15]
When I try to implement two different instances of the input (one for date and one for time separatelly), the popper keeps switching back to the first instance without making a selection. It doesn't matter which one is first, they always switch to the first instance's popper.

The flow is:

- Create two instances of the datepicker
- Open the first one and select anything (or not, but anyway the first instance works fine)
- Open the second one and try to select anything
- Observe the popper transitioning to the first instance

**Comment by erhanfirat** [comment]
I am facing same problem. If I use two instance, poppers conflicts, switch to the first popper while I am on second one.

**Comment by livelybone** [comment]
I'm too busy these days that it's too late to rely. This problem doesn't seem to exist on my side. Here is the screenshot
<img width="336" alt="image" src="https://user-images.githubusercontent.com/13741638/175764509-e5f4e2b9-9a7d-422f-b2c6-98469a365bd7.png">

Can you provide the version of vue and this package that you used?

**Comment by livelybone** [comment]
By the way, I update the example in this repo about this scenario

**Comment by erhanfirat** [comment]
In my case, I am using vue 2 composition api with typescript. 
I have solved it using single instance for both date & time selections.

**Comment by livelybone** [comment]
Ok，I'll test it in this scenario and see if I can reproduce it
