### ISSUE TITLE
The DateRangePicker  does not seem to be able to select a range of days

### ISSUE THREAD

**Issue by xrzhangjmzhang** [livelybone/vue-datepicker#16]
The DateRangePicker  does not seem to be able to select a range of days, Now the minimum interval we can choose is two days.This will bring great trouble to my data screening, may I ask how to solve it. Do I need to change the code somewhere?

**Comment by livelybone** [comment]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/13741638/181867669-737532ef-9441-4365-929c-9b386cf2c368.png">

**Comment by livelybone** [comment]
I fixed this bug in v4.1.2.
