### ISSUE TITLE
dose it suport vue3 + vite?

### ISSUE THREAD

**Issue by tomgor** [livelybone/vue-datepicker#18]
I import this component in vue3 project, and i got this error
![image](https://user-images.githubusercontent.com/12905387/213057801-7f1fc104-67bc-4519-b104-afc4d344505c.png)

so I guess it dosen't support vue3.

**Comment by livelybone** [comment]
No, It doesn't support until I do debugging of vue3 projects. Maybe you can fork this project and modify it yourself.
