### ISSUE TITLE
I can't start week by monday

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [livelybone/vue-datepicker#5]
![image](https://user-images.githubusercontent.com/15924777/75883164-9e46bb00-5e33-11ea-8002-81ccaf658d90.png)

**Comment by livelybone** [comment]
Oh, this component hasn't support this yet. It generates only the standard calendar currently

**Comment by AKopytenko** [comment]
It's rather sad because the "standard calendar" week is defined by the international standard ISO 8601:
> ...
> 2.2.8
> Сalendar week: time interval of seven calendar days starting with a Monday 
> ...

**Comment by livelybone** [comment]
Really T_T ? I'm really sorry about the wrong opinion that Sunday was the first day of the week. 
I'll support custom first day of the week in the next version.

**Comment by livelybone** [comment]
Prop `firstDayOfWeek` is supported in v4.x. Try it! ^_^

**Comment by AKopytenko** [comment]
I don't know if everyone does or not - after updating the package, you can't select a date from the calendar. Reinstalled the package, but the problem remained. After you select a date, the calendar closes, but the date remains the same. The @input event receives an updated date, but the old day is still selected in the calendar (css class "selected").

**Comment by livelybone** [comment]
In v4.x? The [demo](https://livelybone.github.io/vue/vue-datepicker/) works well. Can you show your code here?

> I don't know if everyone does or not - after updating the package, you can't select a date from the calendar. Reinstalled the package, but the problem remained. After you select a date, the calendar closes, but the date remains the same. The @input event receives an updated date, but the old day is still selected in the calendar (css class "selected").
