### ISSUE TITLE
We need to apply bootstrap 4 styles to this component...

### ISSUE THREAD

**Issue by scramatte** [livelybone/vue-datepicker#7]
Hello,

We need to apply bootstrap 4 styles to this component...

Can you add prop to be able to class of input field ? 
Does it possible to remove div wrapper  or at least allow to set class of the div  and add some slots to append / prepend icons, buttons ?

Regards

**Comment by livelybone** [comment]
Thanks, I'll implement prefix/suffix in the next big release. Stay Tune!

About style, I recommend that you apply the style by rewriting it locally

**Comment by livelybone** [comment]
Prefix/suffix slots was added to v4.x which can be used in much the same way as v3
