### ISSUE TITLE
VueJS Warning: Invalid prop type check failed for prop "placeholder"

### ISSUE THREAD

**Issue by mydevlocal** [livelybone/vue-datepicker#8]
Hi, i'm using `Datepicker` component but i'm always getting `placeholder` error, i don't know what is wrong with the configurations, here is my setup in VueJS:

```
<Datepicker
      placeholder="YYYY-MM-DD"
      :dayStr="dayStr"
      :value="start_date"
      @input="pickEndDate"
      :popperProps="popperProps"
/>

[...]
const defaultPopperProps = {
  arrowPosition: 'start',
  arrowOffsetScaling: 1,
  popperOptions: {
    placement: 'bottom-start',
    positionFixed: true,
  },
};

export default {
  name: 'DigitalPlan',

  components: {Datepicker},

  data() {
    return {
      start_date: '',
      dayStr: ['S', 'M', 'T', 'W', 'Th', 'F', 'S'],
      popperProps: defaultPopperProps,
    }
  },
[...]
```

Errors screenshot: [here](https://drive.google.com/file/d/1h9aQJUc9CvRJz9BqZh_lFtkDj4iEcgGA/view?usp=sharing)

Inside the `interface` file [here](https://github.com/livelybone/vue-datepicker/blob/master/index.d.ts) i'm sure that it is an optional `string` but why it needs an `array` instead?

**Comment by livelybone** [comment]
What version do you use?

**Comment by livelybone** [comment]
I cannot open the output you provided

**Comment by livelybone** [comment]
It seems that you want to use placeholder as a formatter?

**Comment by mydevlocal** [comment]
I've updated the output link. I'm using version `^4.0.1` though.
I actually didn't want to use the placeholder, but it still displays an error, so that's why i put it in the component, and again still display an error (please check the error output link)

**Comment by livelybone** [comment]
Can you take a screenshot about that error, I cannot open the output you provided.

**Comment by mydevlocal** [comment]
> Can you take a screenshot about that error, I cannot open the output you provided.

I'm pretty sure the link i've provided is working, it's actually a screenshot

I've also updated the library to the `^4.0.1`, i still get the same error.
**I'm using VueJS v`^2.6.11`

**Comment by mydevlocal** [comment]
Hi @livelybone 
Here is my CodeSandbox link: https://codesandbox.io/s/vuejs-datepicker-fj28f?file=/src/components/HelloWorld.vue

 You can see in the `console` for the error that i report.

**Comment by livelybone** [comment]
Thanks, CodeSandbox link was help. I'll fix it in the next version ^4.0.2

**Comment by livelybone** [comment]
It has been fixed. You can update it to 4.0.2

**Comment by mydevlocal** [comment]
Great, it works now, thank you.
